ERROR <PID 1504:Process-2> myClusterLogger.setmasterdir(): error in mycluster
Traceback (most recent call last):
  File "C:\Users\DPatton\gits\kernelkernel\mycluster.py", line 105, in setmasterdir
    os.mkdir(masterdir)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\DPatton\\gits\\kernelkernel\\cluster_test\\master'
ERROR <PID 9136:Process-4> myClusterLogger.setmasterdir(): error in mycluster
Traceback (most recent call last):
  File "C:\Users\DPatton\gits\kernelkernel\mycluster.py", line 105, in setmasterdir
    os.mkdir(masterdir)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\DPatton\\gits\\kernelkernel\\cluster_test\\master'
